[package]
name = "rwc"
version = "0.1.0"
authors = ["Fuyukiri"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.7"